# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            MKSA
# tagline:          'A Jekyll theme'
description:      ''
baseurl:          /

author:
  name:           'Max Shirokawa'
  url:            https://mksa.tech

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/m-k-S/m-k-S.github.io
